version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Botsome"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
