version: "3.3"

services:
  botsome:
    container_name: botsome
    build: Botsome
    environment:
      Logging__Console__FormatterName: simple
    volumes:
      - botsome:/botsome/
      - ./Botsome/appsettings.json:/app/appsettings.json
  dockergen:
    build:
      context: dockergen
      dockerfile: Dockerfile
    command: -wait 2s -notify-sighup botsome -watch /templates/botsome.tmpl /botsome/bots.json
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - botsome:/botsome/

volumes:
  botsome:
