version: "3.3"

services:
  botsome:
    container_name: botsome
    build: Botsome
    environment:
      Logging__Console__FormatterName: simple
      DOTNET_USE_POLLING_FILE_WATCHER: true
    volumes:
      - ./Botsome/appsettings.json:/app/appsettings.json
