name: Build and push Docker image

on:
  push:
    branches: [ master ]
    paths:
      - 'Botsome/**'
  pull_request:
    paths:
      - 'Botsome/**'

jobs:
  build-botsome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Botsome image
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: botsome
        context: Botsome
        registry: ${{ secrets.PUSH_REPO }}
        username: ${{ secrets.PUSH_USER }}
        password: ${{ secrets.PUSH_PASSWD }}
        default_branch: master
        no_push: ${{ github.event_name == 'pull_request' }}
